### ISSUE TITLE
Buttons Sometimes Shown Incorrectly

### ISSUE THREAD

**Issue by crutchcorn** [solus-project/evopop-gtk-theme#39]
Found an interesting bug on Elementary. 

I use a custom button set up of close on the left and minimize on the right. I do this so I don't accidentally close windows when I meant to minimize them. Anyway, you'll notice that they show incorrectly on GTK 3 applications (showing minimize as close button) yet not metacity apps. 
![screenshot from 2015-04-12 21 25 41](https://cloud.githubusercontent.com/assets/9100169/7109817/0d0dc746-e15b-11e4-9864-65def5b9c29e.png)
And one for the light theme as well
![screenshot from 2015-04-12 21 25 50](https://cloud.githubusercontent.com/assets/9100169/7109816/0d04d38e-e15b-11e4-9ec0-6417bc77ff58.png)
Yet they show fine with Paper GTK theme
![screenshot from 2015-04-12 21 25 55](https://cloud.githubusercontent.com/assets/9100169/7109815/0cffdc58-e15b-11e4-9092-b101d1b0c8db.png)
And if I change to a "Windows" layout everything is fine
![screenshot from 2015-04-12 21 26 06](https://cloud.githubusercontent.com/assets/9100169/7109814/0cf691de-e15b-11e4-842e-06f546276f34.png)

**Comment by poltertec** [comment]
Yep i know.
Is either that or no left window control support in gtk.
There is a fix introduced for this in gtk 3.16.

Grtz

**Comment by crutchcorn** [comment]
There is though. Like I said - works with Paper GTK. Oh well, sorry for bothering. Just something I noticed. :)

**Comment by poltertec** [comment]
Yep but paper isn't using window control assets for its gtk theme as far as i can see only for metacity.
They are controlled by the icon theme. We use assets for that just like the vertex theme for example.
In gtk 3.14 and below this could only be set by using nth-child commands which causes this limitation.
Since 3.16 the window control buttons classes .close , .maximize ,... to resolve this issue.
